### ISSUE TITLE
 pip install  asteroid  error

### ISSUE THREAD

**Issue by shanguanma** [asteroid-team/asteroid#391]
### Before reporting a bug:
First, please search [previous issues](https://github.com/asteroid-team/asteroid/issues)
and [the FAQ](https://asteroid-team.github.io/asteroid/faq.html) and be sure this hasn't
been answered elsewhere.

## 🐛 Bug

I only want to use asteriod as a python package, so I pip install asteroid fellow README.md,
But I got the errors is as follows:
```
[md510@node01 pytorch_ligthning_recipe]$ pip install asteroid
Collecting asteroid
  Using cached asteroid-0.4.0-py3-none-any.whl (221 kB)
Requirement already satisfied: numpy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.18.5)
Requirement already satisfied: pyyaml in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (5.3.1)
Requirement already satisfied: scipy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.5.4)
Requirement already satisfied: torch in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.7.0)
Requirement already satisfied: librosa in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (0.8.0)
Requirement already satisfied: soundfile in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (0.10.3.post1)
Collecting asteroid-filterbanks
  Using cached asteroid_filterbanks-0.3.1-py3-none-any.whl (27 kB)
Requirement already satisfied: torch in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.7.0)
Requirement already satisfied: numpy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.18.5)
Requirement already satisfied: numpy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.18.5)
Requirement already satisfied: numba>=0.43.0 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (0.52.0)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (0.23.2)
Requirement already satisfied: pooch>=1.0 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (1.3.0)
Requirement already satisfied: decorator>=3.0.0 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (4.4.2)
Requirement already satisfied: scipy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.5.4)
Requirement already satisfied: audioread>=2.0.0 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (2.1.9)
Requirement already satisfied: soundfile in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (0.10.3.post1)
Requirement already satisfied: joblib>=0.14 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (0.17.0)
Requirement already satisfied: resampy>=0.2.2 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from librosa->asteroid) (0.2.2)
Requirement already satisfied: numpy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.18.5)
Requirement already satisfied: setuptools in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from numba>=0.43.0->librosa->asteroid) (50.3.2.post20201201)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from numba>=0.43.0->librosa->asteroid) (0.35.0)
Collecting pandas
  Using cached pandas-1.1.5-cp38-cp38-manylinux1_x86_64.whl (9.3 MB)
Requirement already satisfied: python-dateutil>=2.7.3 in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from pandas->asteroid) (2.8.1)
Requirement already satisfied: numpy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.18.5)
Collecting pb-bss-eval
  Using cached pb_bss_eval-0.0.2-py3-none-any.whl (14 kB)
Collecting cached-property
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting einops
  Using cached einops-0.3.0-py2.py3-none-any.whl (25 kB)
Collecting mir-eval
  Using cached mir_eval-0.6-py3-none-any.whl
Requirement already satisfied: numpy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.18.5)
Requirement already satisfied: future in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from mir-eval->pb-bss-eval->asteroid) (0.18.2)
Requirement already satisfied: scipy in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from asteroid) (1.5.4)
Requirement already satisfied: six in /home3/md510/anaconda3/envs/simsiam/lib/python3.8/site-packages (from mir-eval->pb-bss-eval->asteroid) (1.15.0)
Collecting pesq
   Using cached pesq-0.0.1.tar.gz (79 kB)
    ERROR: Command errored out with exit status 1:
     command: /home3/md510/anaconda3/envs/simsiam/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s7c8aune/pesq_e90d1354ce464671a35bd0daea9162b3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s7c8aune/pesq_e90d1354ce464671a35bd0daea9162b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8zerfw39
         cwd: /tmp/pip-install-s7c8aune/pesq_e90d1354ce464671a35bd0daea9162b3/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s7c8aune/pesq_e90d1354ce464671a35bd0daea9162b3/setup.py", line 10, in <module>
        from Cython.Build import cythonize, build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### To Reproduce

```
$ conda create -n asteroid python=3.8
$ conda activate asteroid
$ pip install asteroid
```

Steps to reproduce the behavior (code sample and stack trace):

### Environment
```
[md510@node01 ~]$ conda activate asteroid
[md510@node01 ~]$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

```
#### Package versions

Run `asteroid-versions` and paste the output here:

```
Paste here
```

Alternatively, if you cannot install Asteroid or have an old version that doesn't have the `asteroid-versions` script,
please output the output of:

```
pip freeze | egrep -i 'pytorch|torch|asteroid'
```

#### Additional info

Additional info (environment, custom script, etc...)

**Comment by jonashaag** [comment]
https://github.com/ludlows/python-pesq/issues/14 strikes again :(

Install Cython first.

**Comment by shanguanma** [comment]
Thanks for your reply, I follow your suggestion, before install asteroid, it should first install NumPy and Cython.
```
$ conda create -n asteroid python=3.8
$ conda activate asteroid
$ pip install numpy 
$ pip install Cython
$ pip install asteroid
```
solved, I will close it.

**Comment by xiaofanloveme** [comment]
Thank you, I solved the same problem about asteroid

**Comment by GiorinoGiobana** [comment]
Thank you, I solved the same problem about asteroid🤩
