### ISSUE TITLE
DeepClustering error.

### ISSUE THREAD

**Issue by yangyan008001** [asteroid-team/asteroid#397]
## 🐛 Bug

At the end of the first epoch of training, I meet a error. And I can not handle it.....
Here is the log:

```
Stage 3: Training
/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Checkpoint directory /search/odin/yangyan/asteroid_master/asteroid/egs/wsj0-mix/DeepClustering_1/exp/train_chimera_vox_denoise_min exists and is not empty.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [4,5]

  | Name      | Type        | Params
------------------------------------------
0 | model     | Model       | 36.0 M
1 | loss_func | ChimeraLoss | 0     
------------------------------------------
36.0 M    Trainable params
0         Non-trainable params
36.0 M    Total params
{'data': {'n_src': 2,
          'sample_rate': 8000,
          'train_dir': 'data/2speakers/wav8k/min/tr',
          'valid_dir': 'data/2speakers/wav8k/min/cv'},
 'filterbank': {'kernel_size': 256, 'n_filters': 256, 'stride': 64},
 'main_args': {'exp_dir': 'exp/train_chimera_vox_denoise_min/', 'help': None},
 'masknet': {'dropout': 0.3,
             'embedding_dim': 40,
             'hidden_size': 600,
             'n_layers': 4,
             'rnn_type': 'lstm',
             'take_log': False},
 'optim': {'lr': 0.0001, 'optimizer': 'rmsprop', 'weight_decay': 0.0},
 'positional arguments': {},
 'training': {'batch_size': 32,
              'early_stop': True,
              'epochs': 200,
              'half_lr': True,
              'loss_alpha': 1.0,
              'num_workers': 8}}
Drop 13837 utts(1.52 h) from 225738 (shorter than 32000 samples)
Drop 60 utts(0.01 h) from 1133 (shorter than 32000 samples)
Validation sanity check: 0it [00:00, ?it/s]/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Your val_dataloader has `shuffle=True`, it is best practice to turn this off for validation and test dataloaders.
  warnings.warn(*args, **kwargs)
Epoch 0:   0%|          | 0/6654 [00:00<?, ?it/s] /search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:64: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: The {log:dict keyword} was deprecated in 0.9.1 and will be removed in 1.0.0
Please use self.log(...) inside the lightningModule instead.

# log on a step or aggregate epoch metric to the logger and/or progress bar
# (inside LightningModule)
self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True)
  warnings.warn(*args, **kwargs)
Epoch 0: 100%|#########9| 6653/6654 [1:40:09<00:00,  1.11itTraceback (most recent call last):
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 521, in train
    self.train_loop.run_training_epoch()
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 588, in run_training_epoch
    self.trainer.run_evaluation(test_mode=False)
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 622, in run_evaluation
    deprecated_eval_results = self.evaluation_loop.evaluation_epoch_end()
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 208, in evaluation_epoch_end
    deprecated_results = self.__run_eval_epoch_end(self.num_dataloaders, using_eval_result)
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 266, in __run_eval_epoch_end
    self.trainer.logger_connector.track_metrics_deprecated(eval_results, using_eval_result, self.testing)
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 216, in track_metrics_deprecated
    self.__process_eval_epoch_end_results_and_log_legacy(deprecated_eval_results, test_mode)
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 361, in __process_eval_epoch_end_results_and_log_legacy
    self.__process_eval_epoch_end_results_and_log_legacy_update(
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 319, in __process_eval_epoch_end_results_and_log_legacy_update
    self.trainer.logger_connector.log_metrics(log_metrics, {})
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 182, in log_metrics
    scalar_metrics = self.trainer.metrics_to_scalars(metrics)
  File "/search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/logging.py", line 48, in metrics_to_scalars
    v = v.item()
ValueError: only one element tensors can be converted to Python scalars
```

I am not sure whether is about the environment.

### To Reproduce
just run:

```
./run.sh --stage 3 --tag vox_denoise_min   --id  4,5
```

### Expected behavior

the error disappeared,and the training can go on.

### Environment

python 3.8.5

#### Package versions

```
(asteroid) [@nmyjs_120_119 asteroid]$ pip list
Package                Version             Location
---------------------- ------------------- ---------------------------------------------
absl-py                0.11.0
appdirs                1.4.4
asteroid               0.4.1rc0            /search/odin/yangyan/asteroid_master/asteroid
asteroid-filterbanks   0.3.1
audioread              2.1.9
black                  20.8b1
cached-property        1.5.2
cachetools             4.2.0
certifi                2020.12.5
cffi                   1.14.4
cfgv                   3.2.0
chardet                4.0.0
click                  7.1.2
Cython                 0.29.21
decorator              4.4.2
distlib                0.3.1
einops                 0.3.0
filelock               3.0.12
fsspec                 0.8.5
future                 0.18.2
google-auth            1.24.0
google-auth-oauthlib   0.4.2
grpcio                 1.34.0
identify               1.5.10
idna                   2.10
joblib                 1.0.0
librosa                0.8.0
llvmlite               0.35.0
Markdown               3.3.3
mir-eval               0.6
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
mypy-extensions        0.4.3
nodeenv                1.5.0
numba                  0.52.0
numpy                  1.19.4
oauthlib               3.1.0
olefile                0.46
packaging              20.8
pandas                 1.1.5
pathspec               0.8.1
pb-bss-eval            0.0.2
pesq                   0.0.2
Pillow                 8.0.1
pip                    20.2.4
pooch                  1.3.0
pre-commit             2.9.3
protobuf               3.14.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
pyparsing              2.4.7
pystoi                 0.3.3
python-dateutil        2.8.1
pytorch-lightning      1.1.2
pytorch-ranger         0.1.1
pytz                   2020.4
PyYAML                 5.3.1
regex                  2020.11.13
requests               2.25.1
requests-oauthlib      1.3.0
resampy                0.2.2
rsa                    4.6
scikit-learn           0.24.0
scipy                  1.5.4
setuptools             50.3.0.post20201006
six                    1.15.0
SoundFile              0.10.3.post1
tensorboard            2.4.0
tensorboard-plugin-wit 1.7.0
threadpoolctl          2.1.0
toml                   0.10.2
torch                  1.7.1
torch-optimizer        0.0.1a17
torch-stoi             0.1.1
torchaudio             0.7.2
torchvision            0.8.2
tqdm                   4.54.1
typed-ast              1.4.1
typing-extensions      3.7.4.3
urllib3                1.26.2
virtualenv             20.2.2
Werkzeug               1.0.1
wheel                  0.35.1
```

Run `asteroid-versions` and paste the output here:

```
(asteroid) [@nmyjs_120_119 asteroid]$ asteroid-versions
Asteroid            0.4.1rc0, Git checkout 1dc1c130f5c8 (master), dirty tree
PyTorch             1.7.1
PyTorch-Lightning   1.1.2
```

#### Additional info
i change the distributed_backend from dpp to dp in train.py:

```
#distributed_backend = "ddp" if torch.cuda.is_available() else None
distributed_backend = "dp" if torch.cuda.is_available() else None
```

**Comment by yangyan008001** [comment]
project path:  asteroid/egs/wsj0-mix/DeepClustering

**Comment by jonashaag** [comment]
Please use backticks next time you post, see https://guides.github.com/features/mastering-markdown/#examples -> "Code"

**Comment by jonashaag** [comment]
As to your error, maybe something doesn't work with PL 1 which we recently upgraded to. cc @ilyakava maybe you've run into this issue recently?

**Comment by mpariente** [comment]
Can you put a checkpoint at the output of the loss and check its size? 
It looks like it still has the batch dimension so it cannot be logged.

**Comment by ilyakava** [comment]
> As to your error, maybe something doesn't work with PL 1 which we recently upgraded to. cc @ilyakava maybe you've run into this issue recently?

Yes I did see something similar (`index 0 is out of bounds for axis 0 with size 0` type error), but I just did `vim /search/odin/yangyan/anaconda3/envs/asteroid/lib/python3.8/site-packages/pytorch_lightning/trainer/logging.py` and added some extra conditions there, never investigated.

**Comment by mpariente** [comment]
Closing because stale.
