### ISSUE TITLE
Can't continue training DPRNNTasnet model with Asteroid v0.4.5dev, after training first with v0.4.1

### ISSUE THREAD

**Issue by troubledragon** [asteroid-team/asteroid#460]
### Before reporting a bug:
First, please search [previous issues](https://github.com/asteroid-team/asteroid/issues)
and [the FAQ](https://asteroid-team.github.io/asteroid/faq.html) and be sure this hasn't
been answered elsewhere.

## 🐛 Bug

Can't continue training a DPRNNTasnet model in Asteroid v0.4.5dev, after training it first at v0.4.1, without encountering a runtime error.

### To Reproduce
1. In an environment, install Asteroid source and requirements - master branch at v0.4.1.
Run train.py to train a DPRNNTasnet model for 1 epoch and save a checkpoint to "last.ckpt".

2. In a new environment, install latest Asteroid source and requirements - master branch at v0.4.5dev.
Increase epochs in conf.yml to make sure training can continue.
Run train.py to train a DPRNNTasnet model, with Trainer(resume_from_checkpoint) loading "last.ckpt" saved in previous step.

When training epoch starts, a runtime error is encountered:

Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main(arg_dic)
  File "train.py", line 121, in main
    trainer.fit(system)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 493, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 655, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 434, in optimizer_step
    using_lbfgs=is_lbfgs,
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1384, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 278, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 283, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 160, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/optim/adam.py", line 99, in step
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 1

### Expected behavior
Expected Trainer( resume_from_checkpoint) in v0.4.5dev to load a DPRNNTasnet checkpoint saved by v0.4.1

### Environment
docker container from nvidia/cuda:10.1-base-centos7
python 3.7.9

#### Package versions

asteroid-filterbanks==0.3.2
pytorch-lightning==1.2.2
pytorch-ranger==0.1.1
torch==1.6.0+cu101
torch-optimizer==0.1.0
torch-stoi==0.1.2
torchaudio==0.6.0

#### Additional info

Additional info (environment, custom script, etc...)
[train_and_conf.zip](https://github.com/asteroid-team/asteroid/files/6113417/train_and_conf.zip)

**Comment by mpariente** [comment]
Thanks for the issue. 
Let's try to isolate the problem. Somehow, the problem seems to be related to the optimizer, not directly the model. 

- Can you try to load `from_pretrained` and see if it works? 
- Are the lightning versions the same between the first and second env? And PyTorch? 

Thanks

**Comment by troubledragon** [comment]
>     * Can you try to load from_pretrained and see if it works?

I can instantiate this without errors in the Asteroid v0.4.5dev:
model = DPRNNTasNet.from_pretrained("model_0_4_1.pth")

Where model_0_4_1.pth is a model trained for one epoch in Asteroid v0.4.1.

>     * Are the lightning versions the same between the first and second env? And PyTorch?

The lightning versions are different! Sorry I missed this while troubleshooting.

For the Asteroid 0.4.1 docker image, pytorch-lightning==1.2.1
For the Asteroid 0.4.5dev docker image, pytorch-lightning==1.2.2

Downgrading lightning to v1.2.1 on the Asteroid 0.4.5dev docker image doesn't resolve the issue however.

torch==1.6.0+cu101 for both images

**Comment by mpariente** [comment]
Thanks! 

Can you manually forward the model after `model = DPRNNTasNet.from_pretrained("model_0_4_1.pth")`?
How about backward? 
And then optimizer step?

**Comment by mpariente** [comment]
Any update?

**Comment by mpariente** [comment]
It has been a month, closing.
