### ISSUE TITLE
Error in running asteroid\egs\musdb18\X-UMX\train.py 

### ISSUE THREAD

**Issue by felixCheungcheung** [asteroid-team/asteroid#572]
## 🐛 Bug

Due to the fact that the 1.5.0 version of pytorch-lightning removed the distributed backend, some erorrs occured when running `asteroid\egs\musdb18\X-UMX\train.py`

### To Reproduce

`cd asteroid\egs\musdb18\X-UMX`
`python train.py`

### Expected behavior
Error message:

`Traceback (most recent call last): File "train.py", line 500, in <module> main(arg_dic, plain_args) File "train.py", line 459, in main trainer = pl.Trainer( File "C:\Users\Huicheng Zhang\.conda\envs\xumx\lib\site-packages\pytorch_lightning\trainer\connectors\env_vars_connector.py", line 38, in insert_env_defaults return fn(self, **kwargs) TypeError: __init__() got an unexpected keyword argument 'distributed_backend'`

#### Package versions

Run `asteroid-versions` and paste the output here:

Asteroid            0.5.1
PyTorch             1.10.0+cpu
PyTorch-Lightning   1.5.0

#### Additional info

After reinstalling pytorch-lightning to 1.4.9 the above problem will be solved. However it would be good to upgrade the code to PL 1.5.0

**Comment by JusperLee** [comment]
I think you should change the distributed_backend to strategy
