### ISSUE TITLE
KeyError while evaluating musdb18 (X-UMX)

### ISSUE THREAD

**Issue by jerryuhoo** [asteroid-team/asteroid#679]
Hi, when I tried to run stage 2 in musdb18 recipe, I got this error. Could you provide some advice to solve this error? Thanks!
```
Stage 2: Evaluation
Evaluated results will be saved in:
 /home/yy/asteroid/egs/musdb18/X-UMX/exp/train_xumx_7ef939e3/EvaluateResults_musdb18_testdata
Loading model from: /home/yy/asteroid/egs/musdb18/X-UMX/exp/train_xumx_7ef939e3/best_model.pth
Traceback (most recent call last):
  File "eval.py", line 296, in <module>
    eval_main(
  File "eval.py", line 253, in eval_main
    print(results, file=sys.stderr)
  File "/home/yy/anaconda3/envs/asteroid/lib/python3.8/site-packages/museval/aggregate.py", line 256, in __repr__
    targets = self.df["target"].unique()
  File "/home/yy/anaconda3/envs/asteroid/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/yy/anaconda3/envs/asteroid/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'target'
```

**Comment by jerryuhoo** [comment]
Problem solved
